[package]
name = "compiler"
version = "0.1.0"
authors = ["Thomas <tbre90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
natord = "1.0.9"
runtime = { path = "../runtime" }
